export type StationKind = "technicalCenter" | "workbench" | "pharmacy" | "armorBench";
export type StationStatus = "idle" | "crafting" | "ready" | "uncertain";
export type AccountStatus = "ready" | "needsManualLogin" | "loginFailed" | "uncertain" | "isolated";
export type StationPlan = { kind: StationKind; enabled: boolean; itemName: string; durationMinutes: number; startedAtMs: number | null; finishesAtMs: number | null; status: StationStatus };
export type AmmoTarget = { id: string; name: string; enabled: boolean; seasonal: boolean; order: number; lastSuccessDay: string | null; retryCount: number };
export type AccountPlan = { id: string; qqAccount: string; password: string; wegameId: string; enabled: boolean; initialized: boolean; order: number; status: AccountStatus; stations: StationPlan[]; ammoTargets: AmmoTarget[] };
export type SpecialOpsSettings = { enabled: boolean; paused: boolean; dailyExchangeTime: string; emergencyHotkey: string; accounts: AccountPlan[] };
export type SpecialOpsBootstrap = { settings: SpecialOpsSettings; schedule: { dueAccounts: { accountId: string; stationKinds: StationKind[]; ammoTargetIds: string[] }[]; nextWakeAtMs: number | null }; settingsRevision: number; nowMs: number };
export const STATION_LABELS: Record<StationKind, string> = { technicalCenter: "技术中心", workbench: "工作台", pharmacy: "制药台", armorBench: "防具台" };
